Fix docker-compose.yml syntax (#958)
This commit fixes the following error:

```
$ docker-compose run build make clean
ERROR: The Compose file './docker-compose.yml' is invalid because:
build.environment.TRAVIS contains true, which is an invalid type, it should be a string, number, or a null
```